
##### Setup ######
  desc "Install pod dependencies"
  lane :install_pods do
    cocoapods
  end

# Test
  desc "Runs unit tests"
  lane :unit_tests do |params|
    scan(
	scheme: "EmbeddedSocial",
	device: "iPhone 7 (10.3)"
    )
  end

# Build
lane :build_app do
gym(
scheme: "EmbeddedSocial-Example",
configuration: "Debug",
export_method: "development",
clean: true
)
end

#Launch
lane :launch do
install_pods
unit_tests
build_app
end

